#!/usr/bin/env sh

yabai -m config layout bsp

# window placement behavior
yabai -m config window_placement second_child

# general padding and gaps
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# window animations (optional)
yabai -m config window_opacity off
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff444444

